@startuml
class DataManagerEFM {
    + DataManagerEFM(wipeData:bool)
    + AddTour(tour:Tour) : void
    + AddTourLog(log:TourLog) : void
    + DeleteTour(tour:Tour) : void
    + DeleteTourLog(log:TourLog) : void
    + GetTourLogs(tour:Tour) : ObservableCollection<TourLog>
    + GetTours() : ObservableCollection<Tour>
    + UpdateTour(tour:Tour) : void
    + UpdateTourLog(log:TourLog) : void
}
IDataManager <|-- DataManagerEFM
@enduml
