version: '3.3'
services:
  postgredb:
    container_name: tourplanner
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

  es-node01:
    container_name: es-node01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    restart: always
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300

  kib-01:
    container_name: kib-01
    image: docker.elastic.co/kibana/kibana:8.2.3
    restart: always
    networks:
      - elastic
    ports:
      - 5601:5601

networks:
  default:
    name: postgre-service_default
  elastic:
    name: elastic
