@startuml
class AddTourLogViewModel {
    + Name : string <<get>> <<set>> = "Log"
    + Comment : string <<get>> <<set>>
    + Rating : double <<get>> <<set>>
    + _rating : int
    + NewRating : int <<get>> <<set>>
    + Time : int <<get>> <<set>>
    + Difficulty : double <<get>> <<set>>
    + AddTourLogViewModel(bl:ITourPlannerManager, vm:TourLogsSideListBarViewModel)
    + ChangeStar(parameter:object) : void
    + AddNewTourLog() : void
    + CloseWindow() : void
}
class "ObservableCollection`1"<T> {
}
BaseViewModel <|-- AddTourLogViewModel
AddTourLogViewModel --> "Date" DateTime
AddTourLogViewModel --> "Stars<Brush>" "ObservableCollection`1"
AddTourLogViewModel --> "AddTourLogCommand" ICommand
AddTourLogViewModel --> "CloseWindowCommand" ICommand
AddTourLogViewModel --> "UpdateRatingCommand" ICommand
@enduml
