@startuml
class AddTourViewModel {
    + Name : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + From : string <<get>> <<set>>
    + To : string <<get>> <<set>>
    + AddTourViewModel(bl:ITourPlannerManager, vm:TourSideListBarViewModel)
    + <<async>> AddNewTour() : void
    + CloseWindow() : void
}
class "IEnumerable`1"<T> {
}
BaseViewModel <|-- AddTourViewModel
AddTourViewModel --> "TransportType" TransportType
AddTourViewModel --> "TransportValues<TransportType>" "IEnumerable`1"
AddTourViewModel --> "AddTourCommand" ICommand
AddTourViewModel --> "CloseWindowCommand" ICommand
@enduml
