@startuml
class EditLogViewModel {
    + Name : string <<get>> <<set>>
    + Comment : string <<get>> <<set>>
    + _rating : int
    + Rating : int <<get>> <<set>>
    + Time : int <<get>> <<set>>
    + Difficulty : double <<get>> <<set>>
    + EditLogViewModel(log:TourLog, bl:ITourPlannerManager, vm:TourLogsSideListBarViewModel)
    + UpdateLog() : void
    + CloseWindow() : void
    + ChangeStar(parameter:object) : void
}
class "ObservableCollection`1"<T> {
}
BaseViewModel <|-- EditLogViewModel
EditLogViewModel --> "Date" DateTime
EditLogViewModel --> "Stars<Brush>" "ObservableCollection`1"
EditLogViewModel --> "EditTourLogCommand" ICommand
EditLogViewModel --> "CloseWindowCommand" ICommand
EditLogViewModel --> "UpdateRatingCommand" ICommand
@enduml
