@startuml
class MoreOptionsViewModel {
    + MoreOptionsViewModel(bl:ITourPlannerManager, tourVM:TourSideListBarViewModel, tourLogsVM:TourLogsSideListBarViewModel)
    + <<async>> Import() : void
    + Export() : void
    + CreateSummaryReport() : void
    + CreateSingleTourReport() : void
}
MoreOptionsViewModel --> "ImportCommand" ICommand
MoreOptionsViewModel --> "ExportCommand" ICommand
MoreOptionsViewModel --> "SummaryReportCommand" ICommand
MoreOptionsViewModel --> "SingleTourReportCommand" ICommand
@enduml
