@startuml
class TourSideListBarViewModel {
    +  <<event>> TourBar_SelectionChanged : EventHandler<Tour> 
    + TourSideListBarViewModel(bl:ITourPlannerManager)
    + AddItem() : void
    + EditItem() : void
    + DeleteItem() : void
}
class "ObservableCollection`1"<T> {
}
BaseViewModel <|-- TourSideListBarViewModel
ISideListBarViewModel <|-- TourSideListBarViewModel
TourSideListBarViewModel --> "ListTitle" String
TourSideListBarViewModel --> "SelectedItem" Tour
TourSideListBarViewModel --> "Items<Tour>" "ObservableCollection`1"
TourSideListBarViewModel --> "AddCommand" ICommand
TourSideListBarViewModel --> "EditCommand" ICommand
TourSideListBarViewModel --> "DeleteCommand" ICommand
@enduml
