@startuml
class TourLogsSideListBarViewModel {
    + TourLogsSideListBarViewModel(bl:ITourPlannerManager)
    + AddItem() : void
    + EditItem() : void
    + DeleteItem() : void
}
class "ObservableCollection`1"<T> {
}
BaseViewModel <|-- TourLogsSideListBarViewModel
ISideListBarViewModel <|-- TourLogsSideListBarViewModel
TourLogsSideListBarViewModel --> "ListTitle" String
TourLogsSideListBarViewModel --> "SelectedTour" Tour
TourLogsSideListBarViewModel --> "SelectedItem" TourLog
TourLogsSideListBarViewModel --> "Items<TourLog>" "ObservableCollection`1"
TourLogsSideListBarViewModel --> "AddCommand" ICommand
TourLogsSideListBarViewModel --> "EditCommand" ICommand
TourLogsSideListBarViewModel --> "DeleteCommand" ICommand
@enduml
