@startuml
class TourPlannerManager {
    + TourPlannerManager(dal:IDataManager)
    + AddTour(tour:Tour) : void
    + AddTourLog(log:TourLog) : void
    + DeleteTour(tour:Tour) : void
    + DeleteTourLog(log:TourLog) : void
    + GetTourLogs(tour:Tour) : ObservableCollection<TourLog>
    + GetTours() : ObservableCollection<Tour>
    + UpdateTour(tour:Tour) : void
    + UpdateTourLog(log:TourLog) : void
    + Search(searchtext:string) : List<ElasticTourDocument>
    + <<async>> GetRoute(tour:Tour) : Task<Tour>
    + ExportData(tours:ObservableCollection<Tour>, path:string) : void
    + <<async>> ImportData(fileStream:Stream) : Task<List<Tour>>
    + GenerateTourReport(tour:Tour, path:string) : void
    + GenerateSummaryReport(tours:ObservableCollection<Tour>, path:string) : void
    + CalculateAdditionalAttributes(tour:Tour) : void
}
ITourPlannerManager <|-- TourPlannerManager
@enduml
