@startuml
class ElasticTourDocument {
    + Id : int <<get>> <<set>>
    + Description : String? <<get>> <<set>>
    + ElasticTourDocument(id:int, name:string, description:string, from:string, to:string, logs:ObservableCollection<ElasticTourLog>)
}
class "ObservableCollection`1"<T> {
}
ElasticTourDocument --> "Name" String
ElasticTourDocument --> "From" String
ElasticTourDocument --> "To" String
ElasticTourDocument --> "Logs<ElasticTourLog>" "ObservableCollection`1"
@enduml
