@startuml
class ElasticTourLog {
    + Id : int <<get>>
    + Comment : String? <<get>> <<set>>
    + Difficulty : double <<get>> <<set>> = 0
    + TotalTime : int <<get>> <<set>> = 0
    + Rating : double <<get>> <<set>> = 0
    + ElasticTourLog(id:int, name:string, dateTime:DateTime, comment:string?, difficulty:double, totalTime:int, rating:double)
}
ElasticTourLog --> "Name" String
ElasticTourLog o-> "DateTime" DateTime
@enduml
