@startuml
class TourLog {
    + Id : int <<get>>
    + Comment : String? <<get>> <<set>>
    + Difficulty : double <<get>> <<set>> = 0
    + TotalTime : int <<get>> <<set>> = 0
    + Rating : double <<get>> <<set>> = 0
    + TourLog()
    + TourLog(name:string, relatedTour:Tour, dateTime:DateTime, comment:string?, difficulty:double, totalTime:int, rating:double)
    + TourLog(name:string, relatedTour:Tour)
}
TourLog --> "Name" String
TourLog --> "RelatedTour" Tour
TourLog o-> "DateTime" DateTime
@enduml
