@startuml
interface IConfigManager {
    + GetDBConfig() : string?
    + GetAPIKey() : string?
    + GetESUser() : string?
    + GetESPassword() : string?
    + GetESIndex() : string?
    + GetESFingerprint() : string?
}
@enduml
