@startuml
!include .\\TourPlanner\App.xaml.puml
!include .\\TourPlanner\AssemblyInfo.puml
!include .\\TourPlanner\RelayCommand.puml
!include .\\TourPlanner\RelayCommandWithIndex.puml
!include .\\TourPlanner.BL\DataExporter.puml
!include .\\TourPlanner.BL\DataImporter.puml
!include .\\TourPlanner.BL\ITourPlannerManager.puml
!include .\\TourPlanner.BL\MapQuestAPIHandler.puml
!include .\\TourPlanner.BL\ReportGenerator.puml
!include .\\TourPlanner.BL\TourPlannerManager.puml
!include .\\TourPlanner.DAL\DataManagerEFM.puml
!include .\\TourPlanner.DAL\DataManagerMemoryImpl.puml
!include .\\TourPlanner.DAL\IDataManager.puml
!include .\\TourPlanner.DAL\TourplannerDBContext.puml
!include .\\TourPlanner.Model\ElasticTourDocument.puml
!include .\\TourPlanner.Model\ElasticTourLog.puml
!include .\\TourPlanner.Model\Tour.puml
!include .\\TourPlanner.Model\TourLog.puml
!include .\\TourPlanner.UnitTests\BusinessLayerTests.puml
!include .\\TourPlanner.UnitTests\ProjectSetupTests.puml
!include .\\TourPlanner.UnitTests\Usings.puml
!include .\\TourPlanner\Service\BooleanToVisibilityConverter.puml
!include .\\TourPlanner\Service\DialogService.puml
!include .\\TourPlanner\Service\StarColorConverter.puml
!include .\\TourPlanner\ViewModels\AddTourLogViewModel.puml
!include .\\TourPlanner\ViewModels\AddTourViewModel.puml
!include .\\TourPlanner\ViewModels\BaseViewModel.puml
!include .\\TourPlanner\ViewModels\BindingProxy.puml
!include .\\TourPlanner\ViewModels\EditLogViewModel.puml
!include .\\TourPlanner\ViewModels\EditTourViewModel.puml
!include .\\TourPlanner\ViewModels\ISideListBarViewModel.puml
!include .\\TourPlanner\ViewModels\MainViewModel.puml
!include .\\TourPlanner\ViewModels\MoreOptionsViewModel.puml
!include .\\TourPlanner\ViewModels\TourDetailViewModel.puml
!include .\\TourPlanner\ViewModels\TourLogsDetailViewModel.puml
!include .\\TourPlanner\ViewModels\TourLogsSideListBarViewModel.puml
!include .\\TourPlanner\ViewModels\TourSideListBarViewModel.puml
!include .\\TourPlanner\Views\AddNewTourForm.xaml.puml
!include .\\TourPlanner\Views\AddTourLogForm.xaml.puml
!include .\\TourPlanner\Views\EditLogForm.xaml.puml
!include .\\TourPlanner\Views\EditTourForm.xaml.puml
!include .\\TourPlanner\Views\ImportExportButton.xaml.puml
!include .\\TourPlanner\Views\MainWindow.xaml.puml
!include .\\TourPlanner\Views\MoreOptionsButton.xaml.puml
!include .\\TourPlanner\Views\SideListBar.xaml.puml
!include .\\TourPlanner\Views\TourDetailView.xaml.puml
!include .\\TourPlanner\Views\TourLogsDetailView.xaml.puml
!include .\\TourPlanner.DAL\Configuration\ConfigManager.puml
!include .\\TourPlanner.DAL\Configuration\IConfigManager.puml
!include .\\TourPlanner.DAL\ElasticSearch\ElasticSearchService.puml
!include .\\TourPlanner.DAL\Logging\ILoggerWrapper.puml
!include .\\TourPlanner.DAL\Logging\Log4NetWrapper.puml
!include .\\TourPlanner.DAL\Logging\LoggerFactory.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\App.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\App.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\GeneratedInternalTypeHelper.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\GeneratedInternalTypeHelper.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0djptlzx_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0gqosokd_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0kjjztqv_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0mw1tbz1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0nkrgbjd_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0qjozhcp_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0svjh1ak_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0y1zahcr_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_0zmk0zn5_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_11fwx3dn_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_15lacvuf_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_1aikqcbv_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_1aqx5aka_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_1sii4o5l_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_1tzdjqhv_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_23opiuzm_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_24tgugfc_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_2doez2a1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_2nmqvmer_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_2ubsatij_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_30njn41b_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_3gt1f2ze_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_3iwwtkxg_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_3lwdqjv4_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_3myij5hr_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_3rerr5g5_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_3w0puooq_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_403pbo5i_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_40qtrhpr_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_4b4m4n0g_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_4fyj53cd_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_4qmg1rax_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_4ruruuqq_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_512t3djt_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_5a1g0ros_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_5l3mz3tb_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_5mnxaj2d_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_5zshvnau_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_aauo3atj_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_aek4vx3z_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_aem10m5w_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_af3x3fdg_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ah2wppbv_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_aictz5cu_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ajnayd0g_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_amnjjony_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_anchgkun_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_atvpntfu_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_b4goooto_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_bdbjivpz_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_bflogxso_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_bgcjbofh_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_brhj5gph_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_c113cogu_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_c22flyjo_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ccc35pr1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_cewdz0ep_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_cjetg5u3_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_cqoqw0l5_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_cqsjmjum_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_cwhgzeux_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_cxejueja_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_cygxzzvv_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_cz05q1op_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_d0yatq4f_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_de3w04e0_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_dofswiij_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_dq1sem1t_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_dvfyyfgu_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_dwqzapba_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_dxfaqpzh_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_e2nlsbbe_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_e3cuzr2s_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_e51ywusf_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ebr2jfjp_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_eesdbg3d_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_eneaddxc_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_eqzjqwm4_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_f5ehg4bx_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_faycwku1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_fre4k24h_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_frfyyqnp_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_fwleuwzp_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_fzfwyhix_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_g522f0dp_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_garwlhwj_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_gcibviwj_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ggfqcvb1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_gh1gi5n5_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_gkogro42_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_gtrti3qn_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_h0kpmepn_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_hcjtn0iu_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_helx4fwj_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_hfcz1gy2_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_hfedniry_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_hfopzw2h_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_hrbgu5gr_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_huqgq2gl_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_i1fcnv4z_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_i1mobgtv_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_i44v0qfi_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_i4ymexba_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_iaj51zeb_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_itmrbsuo_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_j4rotdct_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_jnq5enc5_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_jvir5wtl_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ka53t5u1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ketvql2i_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_kf2ncl1r_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_khb4wdaq_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ko5la0d0_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_kpf3mqfl_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_kv21pufd_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_kwn11v0m_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_kzvx0ktj_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_l1brgp1o_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_l1clbwhq_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_l2h5xeqy_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_lcryjhd5_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ldf4dlud_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_liom4tcv_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_lmf12rth_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_lnookdv4_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_losqbxxs_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_lttsod0m_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_lujfzxgn_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_mfllxl2z_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_mlt2y55r_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_mskvc0fw_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_msocncyk_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_mvbhlswi_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ndoh13wc_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_nj2dufpf_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_obr5li1v_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_okq31z1q_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_oojw4v1g_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_osmooy0w_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_otbp1cot_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_oxxfd4pt_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ozel1ftm_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ozukdz0g_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_p1b0rpcn_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ph1pmb3c_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_pkn3njq1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_q2xy0xkt_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_q5amm2qx_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_qjdmp5ix_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_qkm3jm5j_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_qnkwdb3i_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_qny5aty0_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_qpmbihfn_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_qq3w4eqp_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_qyfam2id_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_qzj2g5fu_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rar33tjo_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rmdonaz2_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rp5pm0e3_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rrf0guc1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rs0mztwu_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rsvdqy3l_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rugep041_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rugowvyl_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_rwjaphsn_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_s1444gla_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_s1jpzrnh_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_sa230xp5_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_sdjkg1ls_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_sgwz4mpl_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_srm4lwap_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_stt5lhi0_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_szjvsnc2_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_t10itij5_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_tqae4oxn_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_tsgvpil1_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_tuspa1i2_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ullcz2da_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_upc3va3t_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_v2y5tzns_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_v3ek0poh_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_v5ydx4sd_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_vbbmlnsg_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_vk2b1npz_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_vx4u4ppa_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_wwi5v0ni_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_wzyaxjre_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_x4sqoqat_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_xbbuzn1l_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_xby5ppqh_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_xlrp1zqb_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_xsjguwpl_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_xw4fatjm_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_y3dzx55w_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_y3xnfb0l_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_y5kgxbeu_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ydhc1w1q_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_yh4epo0m_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_yijherxj_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ykxlvw3i_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ykyrenip_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_ypapiwe0_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_yt5qweci_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_zcizbnz2_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\TourPlanner.UI_zsvtheim_wpftmp.AssemblyInfo.puml
!include .\\TourPlanner.BL\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\TourPlanner.BL\obj\Debug\net7.0\TourPlanner.BL.AssemblyInfo.puml
!include .\\TourPlanner.BL\obj\Debug\net7.0\TourPlanner.BL.GlobalUsings.g.puml
!include .\\TourPlanner.DAL\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\TourPlanner.DAL\obj\Debug\net7.0\TourPlanner.DAL.AssemblyInfo.puml
!include .\\TourPlanner.DAL\obj\Debug\net7.0\TourPlanner.DAL.GlobalUsings.g.puml
!include .\\TourPlanner.Model\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\TourPlanner.Model\obj\Debug\net7.0\TourPlanner.Model.AssemblyInfo.puml
!include .\\TourPlanner.Model\obj\Debug\net7.0\TourPlanner.Model.GlobalUsings.g.puml
!include .\\TourPlanner.UnitTests\obj\Debug\net7.0-windows\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\TourPlanner.UnitTests\obj\Debug\net7.0-windows\TourPlanner.UnitTests.AssemblyInfo.puml
!include .\\TourPlanner.UnitTests\obj\Debug\net7.0-windows\TourPlanner.UnitTests.GlobalUsings.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\AddNewTourForm.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\AddNewTourForm.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\AddTourLogForm.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\AddTourLogForm.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\EditLogForm.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\EditLogForm.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\EditTourForm.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\EditTourForm.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\ImportExportButton.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\ImportExportButton.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\MainWindow.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\MainWindow.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\MoreOptionsButton.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\MoreOptionsButton.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\SideListBar.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\SideListBar.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\TourDetailView.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\TourDetailView.g.i.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\TourLogsDetailView.g.puml
!include .\\TourPlanner\obj\Debug\net7.0-windows\Views\TourLogsDetailView.g.i.puml
@enduml
