@startuml
class ElasticSearchService {
    + ElasticSearchService()
    + CheckConnection() : bool
    + <<async>> IndexTourDocument(tour:Tour) : Task<string>
    + FuzzySearch(givenString:string) : List<ElasticTourDocument>
    + GetElasticTourDocumentById(id:int) : ElasticTourDocument
    + AddTourLog(tour:ElasticTourDocument) : bool
    + UpdateTour(tourid:int, newName:string, newDescription:string) : bool
    + UpdateTourLog(tourid:int, logId:int, newName:string, newComment:string, newRating:double, newTotalTime:int, newDate:DateTime, newDifficulty:double) : bool
    + DeleteLogById(tourId:int, logId:int) : bool
    + DeleteTourDocument(id:string) : bool
}
ElasticSearchService --> "Instance" ElasticSearchService
@enduml
